from tkinter import ttk , constants as con , Text , filedialog
from base_window import base_window
#firm_id, firm_suffix, firm_name, firm_email, firm_address, firm_mobile, firm_website, firm_gstin, firm_pan, firm_bank, firm_accno, firm_ifsc, firm_tax, insert_time, insert_id, update_time, update_id
class firm(base_window):
    def __init__(self , root ,frames , dmsn , lbls ,title,validations):
        base_window.__init__(self , root ,frames , dmsn , lbls ,title)
        base_window.main_frame.grid_propagate(False)
        self.main_hgt = base_window.main_frame.winfo_reqheight()
        self.main_wdt = base_window.main_frame.winfo_reqwidth()
        self.combo_values = ["REGULAR" , "COMPOSITION" , "CASH"]

        self.lbl_firm_tax = ttk.Label(base_window.main_frame , text = "Tax Method        :" , style = "window_text_medium.TLabel")
        self.lbl_firm_name = ttk.Label(base_window.main_frame , text = "Firm Name         :" , style = "window_text_medium.TLabel")
        self.lbl_firm_suff_txt = ttk.Label(base_window.main_frame , text = "Firm Suffix       :" , style = "window_text_medium.TLabel")
        self.lbl_firm_email = ttk.Label(base_window.main_frame , text = "Firm Email        :" , style = "window_text_medium.TLabel")
        self.lbl_firm_mob = ttk.Label(base_window.main_frame , text = "Firm Mobile       :" , style = "window_text_medium.TLabel")
        self.lbl_firm_web = ttk.Label(base_window.main_frame , text = "Firm Website      :" , style = "window_text_medium.TLabel")
        self.lbl_firm_address = ttk.Label(base_window.main_frame , text = "Firm Address      :" , style = "window_text_medium.TLabel")
        self.lbl_firm_gstin = ttk.Label(base_window.main_frame , text = "Firm GSTIN        :" , style = "window_text_medium.TLabel")
        self.lbl_firm_pan = ttk.Label(base_window.main_frame , text = "Firm PAN          :" , style = "window_text_medium.TLabel")
        self.lbl_firm_bank = ttk.Label(base_window.main_frame , text = "Firm Bank Name    :" , style = "window_text_medium.TLabel")
        self.lbl_firm_ifsc = ttk.Label(base_window.main_frame , text = "Firm Bank IFSC    :" , style = "window_text_medium.TLabel")
        self.lbl_firm_accno = ttk.Label(base_window.main_frame , text = "Firm Bank AC/NO   :" , style = "window_text_medium.TLabel")
        self.lbl_firm_upiid = ttk.Label(base_window.main_frame , text = "Firm UPI ID       :" , style = "window_text_medium.TLabel")
        self.lbl_firm_upiqr = ttk.Label(base_window.main_frame , text = "Firm UPI QR       :" , style = "window_text_medium.TLabel")
        self.lbl_firm_logo = ttk.Label(base_window.main_frame , text = "Firm Logo         :" , style = "window_text_medium.TLabel")
        self.lbl_firm_photo = ttk.Label(base_window.main_frame , text = "Firm Photo        :" , style = "window_text_medium.TLabel")

        self.combo_tax = ttk.Combobox(self.main_frame  ,values = self.combo_values, font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , width = 30) 
        self.combo_tax.bind("<FocusOut>" , self.combo_entry_out)
        self.combo_tax.insert(0,self.combo_values[0])
        self.ent_firm_name = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_name.bind("<FocusOut>" , self.combo_entry_out)
        self.lbl_firm_suff = ttk.Label(base_window.main_frame , width = 30, background = "#fff" ,relief = con.SOLID , borderwidth = 1 , border = 1 , font = ('Lucida Grande' , -int(self.main_hgt*0.03)))
        self.ent_firm_email = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[1], '%P'))
        self.ent_firm_email.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_mob = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_mob.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_web = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_web.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_address = Text(self.main_frame  , width = 30 , height = 4 ,  font = ('Lucida Grande' , -int(self.main_hgt*0.03)))
        self.ent_firm_gstin = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_gstin.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_pan = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_pan.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_bank = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_bank.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_ifsc = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_ifsc.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_accno = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[0], '%P'))
        self.ent_firm_accno.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_upiid = ttk.Entry(self.main_frame  , width = 30 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) , validate="key", validatecommand=(validations[1], '%P'))
        self.ent_firm_upiid.bind("<FocusOut>" , self.combo_entry_out)
        self.ent_firm_upiqr = ttk.Entry(self.main_frame  , width = 20 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)))
        self.ent_firm_upiqr.bind("<FocusOut>" , self.combo_entry_out)
        self.btn_firm_upiqr = ttk.Button(self.main_frame , text = "Browse" , style = "window_btn_medium.TButton" ,command = lambda : self.file_dialog_qr(None))
        self.btn_firm_upiqr.bind("<Return>" , self.file_dialog_qr)
        self.ent_firm_logo = ttk.Entry(self.main_frame  , width = 20 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)) )
        self.ent_firm_logo.bind("<FocusOut>" , self.combo_entry_out)
        self.btn_firm_logo = ttk.Button(self.main_frame , text = "Browse" , style = "window_btn_medium.TButton" ,command = lambda : self.file_dialog_logo(None))
        self.btn_firm_logo.bind("<Return>" , self.file_dialog_logo)
        self.ent_firm_photo = ttk.Entry(self.main_frame  , width = 20 ,   font = ('Lucida Grande' , -int(self.main_hgt*0.03)))
        self.ent_firm_photo.bind("<FocusOut>" , self.combo_entry_out)
        self.btn_firm_photo = ttk.Button(self.main_frame , text = "Browse" , style = "window_btn_medium.TButton" ,command = lambda : self.file_dialog_photo(None))
        self.btn_firm_photo.bind("<Return>" , self.file_dialog_photo)

        self.lbl_firm_tax.grid(row = 0 , column = 0 , pady = int(self.main_hgt*0.01))
        self.combo_tax.grid(row = 0 , column = 1 , columnspan = 2)
        self.lbl_firm_name.grid(row = 1 , column = 0 , pady = int(self.main_hgt*0.012))
        self.ent_firm_name.grid(row = 1 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_suff_txt.grid(row = 2 , column = 0 , pady = int(self.main_hgt*0.01))
        self.lbl_firm_suff.grid(row = 2 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_email.grid(row = 3 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_email.grid(row = 3 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_mob.grid(row = 4 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_mob.grid(row = 4 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_web.grid(row = 5 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_web.grid(row = 5 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_address.grid(row = 6 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_address.grid(row = 6 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_gstin.grid(row = 7 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_gstin.grid(row = 7 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_pan.grid(row = 8 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_pan.grid(row = 8 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_bank.grid(row = 9 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_bank.grid(row = 9 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_ifsc.grid(row = 10 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_ifsc.grid(row = 10 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_accno.grid(row = 11 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_accno.grid(row = 11 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_upiid.grid(row = 12 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_upiid.grid(row = 12 , column = 1 , columnspan = 2 , sticky = con.W)
        self.lbl_firm_upiqr.grid(row = 13 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_upiqr.grid(row = 13 , column = 1 , sticky = con.W)
        self.btn_firm_upiqr.grid(row = 13 , column = 2)
        self.lbl_firm_logo.grid(row = 14 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_logo.grid(row = 14 , column = 1 , sticky = con.W)
        self.btn_firm_logo.grid(row = 14 , column = 2)
        self.lbl_firm_photo.grid(row = 15 , column = 0 , pady = int(self.main_hgt*0.01))
        self.ent_firm_photo.grid(row = 15 , column = 1 , sticky = con.W)
        self.btn_firm_photo.grid(row = 15 , column = 2)


    def combo_entry_out(self , e):
        e.widget.select_clear()

    def file_dialog_qr(self , e):
        file = filedialog.askopenfilename(initialdir = "/",title = "Select a File",filetypes = [["Image ","*.*"]])
        self.ent_firm_upiqr.delete(0,con.END)
        self.ent_firm_upiqr.insert(con.END,str(file))
        

    def file_dialog_logo(self , e):
        file = filedialog.askopenfilename(initialdir = "/",title = "Select a File",filetypes = [["Image ","*.*"]])
        self.ent_firm_logo.delete(0,con.END)
        self.ent_firm_logo.insert(0,file)

    def file_dialog_photo(self , e):
        file = filedialog.askopenfilename(initialdir = "/",title = "Select a File",filetypes = [["Image ","*.*"]])
        self.ent_firm_photo.delete(0,con.END)
        self.ent_firm_photo.insert(0,file)